### ISSUE TITLE
expected return type is different from actual return type  

### ISSUE THREAD

**Issue by KaiGrassnick** [godruoyi/php-snowflake#10]
Hello,

there is a problem in the consistency of the defined return type.
Expected: Int, Given String.

PHPDoc gives the hint, that the return type will be of type `int`

```php
    /**
     * Get snowflake id.
     *
     * @return int
     */
    public function id()
    {
```
([source](https://github.com/godruoyi/php-snowflake/blob/master/src/Snowflake.php#L79))

Actual return is casted to string
```php
        return (string) ((($currentTime - $this->getStartTimeStamp()) << $timestampLeftMoveLength)
            | ($this->datacenter << $datacenterLeftMoveLength)
            | ($this->workerid << $workerLeftMoveLength)
            | ($sequence));
```
([source](https://github.com/godruoyi/php-snowflake/blob/master/src/Snowflake.php#L93))

**Comment by godruoyi** [comment]
In order to resolve precision for php int type, we designed the return type to be string  at the beginning.

so the PHPDoc description is incorrect, which I have fixed in [this commit](https://github.com/godruoyi/php-snowflake/commit/4c73869e20ee4534bf867efa46dc294ba6578b73).

and thank you tell me this issues.
